// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Miniflux
{
    [MinifluxResourceType("miniflux:index:MinifluxService")]
    public partial class MinifluxService : Pulumi.ComponentResource
    {
        /// <summary>
        /// The URL of the Miniflux service.
        /// </summary>
        [Output("endpoint")]
        public Output<string> Endpoint { get; private set; } = null!;


        /// <summary>
        /// Create a MinifluxService resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MinifluxService(string name, MinifluxServiceArgs args, ComponentResourceOptions? options = null)
            : base("miniflux:index:MinifluxService", name, args ?? new MinifluxServiceArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class MinifluxServiceArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Miniflux administrator's password.
        /// </summary>
        [Input("adminPassword", required: true)]
        public Input<string> AdminPassword { get; set; } = null!;

        /// <summary>
        /// The username to use for the Miniflux service administrator account.
        /// </summary>
        [Input("adminUsername")]
        public Input<string>? AdminUsername { get; set; }

        /// <summary>
        /// The name of the PostgreSQL database to be used by Miniflux.
        /// </summary>
        [Input("dbName")]
        public Input<string>? DbName { get; set; }

        /// <summary>
        /// The PostgreSQL user's password.
        /// </summary>
        [Input("dbPassword", required: true)]
        public Input<string> DbPassword { get; set; } = null!;

        /// <summary>
        /// The username of the PostgreSQL account to be used by the Miniflux service.
        /// </summary>
        [Input("dbUsername")]
        public Input<string>? DbUsername { get; set; }

        public MinifluxServiceArgs()
        {
            AdminUsername = "admin";
            DbName = "miniflux";
            DbUsername = "miniflux";
        }
    }
}
