# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_miniflux.service as service
else:
    service = _utilities.lazy_import('pulumi_miniflux.service')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "miniflux",
  "mod": "service",
  "fqn": "pulumi_miniflux.service",
  "classes": {
   "miniflux:service:MinifluxService": "MinifluxService"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "miniflux",
  "token": "pulumi:providers:miniflux",
  "fqn": "pulumi_miniflux",
  "class": "Provider"
 }
]
"""
)
